channels:
- conda-forge
dependencies:
- python=3.10
- pip
- pip:
  - mlflow
  - cloudpickle
  - numpy
  - pandas
  - psutil
  - pyarrow
  - scikit-learn
  - scipy
  - azureml-inference-server-http
name: mlflow-env
